<a href="https://colab.research.google.com/github/Akash14-09/Machine_Learning/blob/main/Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Why can we not rely on Train Test Split


In [1]:
from sklearn.datasets import load_iris
import numpy as np

In [2]:
data = load_iris()
X = data['data']
y = data['target']

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score



In [6]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.3 , random_state = 4)
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test,y_pred)

0.9777777777777777

Here you can see the problem by urself that when you change value of random_state then the accruracy score changes significantly .
So one solution we can apply the loop wise values for the random_state but it wont be optimal for optimal we would be using KFold Cross Validation

##KFold Cross Validation

In [7]:
from sklearn.model_selection import KFold

In [8]:
X = np.random.random(size = (25 , 5))
y = np.random.randint(low = 0 , high = 2 , size = 25)

In [9]:
X

array([[0.11256179, 0.9075505 , 0.66996938, 0.40674206, 0.26601131],
       [0.46561708, 0.73132019, 0.40375602, 0.32325676, 0.35232897],
       [0.89422523, 0.31121849, 0.98721837, 0.02049685, 0.43178254],
       [0.93638504, 0.69161606, 0.94754807, 0.02802702, 0.29883664],
       [0.800018  , 0.72295945, 0.89213467, 0.60749871, 0.32195232],
       [0.34245304, 0.69587713, 0.84733462, 0.74334069, 0.11267707],
       [0.67605672, 0.64222521, 0.35368346, 0.09530077, 0.45778234],
       [0.18563296, 0.01484965, 0.65557009, 0.95952274, 0.8968572 ],
       [0.93047543, 0.95234252, 0.10282557, 0.19824638, 0.15628947],
       [0.60176216, 0.48105172, 0.38321564, 0.26634934, 0.12165554],
       [0.30274528, 0.95432428, 0.42091035, 0.97439299, 0.17511358],
       [0.06590114, 0.16561554, 0.07489754, 0.14989074, 0.99118215],
       [0.52696773, 0.48785261, 0.58303905, 0.02717949, 0.33377699],
       [0.881351  , 0.47366061, 0.78033193, 0.95950737, 0.36696419],
       [0.47001613, 0.08175937, 0.

In [10]:
y

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1])

In [11]:
kf = KFold(n_splits = 6)
for train_index , test_index in kf.split(X):
  print("Train Index : " , train_index , "Test Index : " , test_index)

Train Index :  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] Test Index :  [0 1 2 3 4]
Train Index :  [ 0  1  2  3  4  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] Test Index :  [5 6 7 8]
Train Index :  [ 0  1  2  3  4  5  6  7  8 13 14 15 16 17 18 19 20 21 22 23 24] Test Index :  [ 9 10 11 12]
Train Index :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 17 18 19 20 21 22 23 24] Test Index :  [13 14 15 16]
Train Index :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 21 22 23 24] Test Index :  [17 18 19 20]
Train Index :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] Test Index :  [21 22 23 24]


##What if there are unqual proportions of clasees in the Test Set?

####cross_val_score(classification)

In [12]:
from sklearn.model_selection import cross_val_score

In [13]:
data = load_iris()
X = data['data']
y = data['target']

In [15]:
knn = KNeighborsClassifier(n_neighbors = 5)
scores = cross_val_score(knn , X , y , cv = 10 , scoring = 'accuracy')
print(scores)

[1.         0.93333333 1.         1.         0.86666667 0.93333333
 0.93333333 1.         1.         1.        ]


In [16]:
scores.mean()

np.float64(0.9666666666666668)

In [17]:
for i in range(1,21) :
  knn = KNeighborsClassifier(n_neighbors = i)
  scores = cross_val_score(knn , X , y , cv = 10 , scoring = 'accuracy')
  print(i , scores.mean())

1 0.96
2 0.9533333333333334
3 0.9666666666666666
4 0.9666666666666666
5 0.9666666666666668
6 0.9666666666666668
7 0.9666666666666668
8 0.9666666666666668
9 0.9733333333333334
10 0.9666666666666668
11 0.9666666666666668
12 0.9733333333333334
13 0.9800000000000001
14 0.9733333333333334
15 0.9733333333333334
16 0.9733333333333334
17 0.9733333333333334
18 0.9800000000000001
19 0.9733333333333334
20 0.9800000000000001


###cross_val_score(regression)

In [19]:
#not able to write code because load_boston has been removed from the recent version of slickit learn