<a href="https://colab.research.google.com/github/Akash14-09/Machine_Learning/blob/main/MICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

In [7]:
from sklearn.linear_model import LinearRegression

In [26]:
df = np.round(pd.read_csv('/content/50_Startups.csv')[['R&D Spend','Administration'  , 'Marketing Spend' , 'Profit']]/1000)


In [28]:
df.head()

,R&D Spend,Administration,Marketing Spend,Profit
0,165.0,137.0,472.0,192.0
1,163.0,151.0,444.0,192.0
2,153.0,101.0,408.0,191.0
3,144.0,119.0,383.0,183.0
4,142.0,91.0,366.0,166.0


In [10]:
np.random.seed(9)

In [11]:
df = df.sample(5)

In [12]:
df

,R&D Spend,Administration,Marketing Spend,Profit
21,78.0,154.0,300.0,111.0
37,44.0,51.0,197.0,90.0
2,153.0,101.0,408.0,191.0
14,120.0,157.0,257.0,133.0
44,22.0,155.0,28.0,65.0


In [13]:
df = df.iloc[: , 0 : -1]
df

,R&D Spend,Administration,Marketing Spend
21,78.0,154.0,300.0
37,44.0,51.0,197.0
2,153.0,101.0,408.0
14,120.0,157.0,257.0
44,22.0,155.0,28.0


In [14]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

/tmp/ipykernel_1078/766688332.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/tmp/ipykernel_1078/766688332.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/tmp/ipykernel_1078/766688332.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan


In [15]:
df.head()

,R&D Spend,Administration,Marketing Spend
21,78.0,154.0,300.0
37,NaN,51.0,197.0
2,153.0,101.0,408.0
14,120.0,NaN,257.0
44,22.0,155.0,NaN


In [16]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [18]:
df0
#0th iteration

,R&D Spend,Administration,Marketing Spend
21,78.00,154.00,300.0
37,93.25,51.00,197.0
2,153.00,101.00,408.0
14,120.00,115.25,257.0
44,22.00,155.00,290.5


In [19]:
df1 = df0.copy()
df1.iloc[1,0] = np.nan
df1

,R&D Spend,Administration,Marketing Spend
21,78.0,154.00,300.0
37,NaN,51.00,197.0
2,153.0,101.00,408.0
14,120.0,115.25,257.0
44,22.0,155.00,290.5


Stage 1 --> When there is no missing values in the dataset
Note --> First prediction would be done witht the mean values then as we move further we keep predicting with the ml algorithm again and again and we keep changing our base dataset , by doing so we'll keep going more closer to the correct value


In [20]:
#use first three rows to build a model and use the last row for the prediction

X = df1.iloc[[0,2,3,4] , 1: 3]
X

,Administration,Marketing Spend
21,154.00,300.0
2,101.00,408.0
14,115.25,257.0
44,155.00,290.5


In [22]:
y = df1.iloc[[0,2,3,4],0]
y

,R&D Spend
21,78.0
2,153.0
14,120.0
44,22.0


In [23]:
lr = LinearRegression()

lr.fit(X,y)

lr.predict(df1.iloc[1,1:].values.reshape(1,2))


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([230.50836125])

In [29]:
df1.iloc[1,0] = 230.50

In [30]:
df1

,R&D Spend,Administration,Marketing Spend
21,78.0,154.00,300.0
37,230.5,51.00,197.0
2,153.0,101.00,408.0
14,120.0,115.25,257.0
44,22.0,155.00,290.5


In [31]:
#remove the column two imputed value
df1.iloc[3,1] = np.nan
df1

,R&D Spend,Administration,Marketing Spend
21,78.0,154.0,300.0
37,230.5,51.0,197.0
2,153.0,101.0,408.0
14,120.0,NaN,257.0
44,22.0,155.0,290.5


In [32]:
#using the last three rows to build a model and use the first one for the prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

,R&D Spend,Marketing Spend
21,78.0,300.0
37,230.5,197.0
2,153.0,408.0
44,22.0,290.5


In [33]:
y = df1.iloc[[0,1,2,4], 1]
y

,Administration
21,154.0
37,51.0
2,101.0
44,155.0


In [34]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([113.55563522])

In [35]:
df1.iloc[3,1] = 113.55

In [36]:
df1

,R&D Spend,Administration,Marketing Spend
21,78.0,154.00,300.0
37,230.5,51.00,197.0
2,153.0,101.00,408.0
14,120.0,113.55,257.0
44,22.0,155.00,290.5


In [37]:
#remove the column three imputed value
df1.iloc[4,-1] = np.nan
df1

,R&D Spend,Administration,Marketing Spend
21,78.0,154.00,300.0
37,230.5,51.00,197.0
2,153.0,101.00,408.0
14,120.0,113.55,257.0
44,22.0,155.00,NaN


In [38]:
#use the last three rows to build a model and use the first one for the prediction
X = df1.iloc[0: 4 , 0: 2]
X

,R&D Spend,Administration
21,78.0,154.00
37,230.5,51.00
2,153.0,101.00
14,120.0,113.55


In [39]:
y= df1.iloc[0: 4 , -1]
y

,Marketing Spend
21,300.0
37,197.0
2,408.0
14,257.0


In [40]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([264.02820283])

In [41]:
df1.iloc[4,-1] = 264.02

In [42]:
#after the first iteration
df1

,R&D Spend,Administration,Marketing Spend
21,78.0,154.00,300.00
37,230.5,51.00,197.00
2,153.0,101.00,408.00
14,120.0,113.55,257.00
44,22.0,155.00,264.02


In [43]:
#subtract the 0th iteration from the first one
df1 - df0

,R&D Spend,Administration,Marketing Spend
21,0.00,0.0,0.00
37,137.25,0.0,0.00
2,0.00,0.0,0.00
14,0.00,-1.7,0.00
44,0.00,0.0,-26.48


In [44]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan
df2

,R&D Spend,Administration,Marketing Spend
21,78.0,154.00,300.00
37,NaN,51.00,197.00
2,153.0,101.00,408.00
14,120.0,113.55,257.00
44,22.0,155.00,264.02


In [45]:
X = df2.iloc[[0,2,3,4] , 1: 3]
y = df2.iloc[[0,2,3,4] , 0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([205.53104122])

In [46]:
df2.iloc[1,0] = 205.53

In [48]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4] , [0,2]]
y = df2.iloc[[0,2,3,4] , 0]


lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([96.06053691])

In [49]:
df2.iloc[3,1] = 96.06

In [50]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0: 4 , 0:2]
y = df2.iloc[0: 4 , -1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([229.35477958])

In [51]:
df2.iloc[4,-1] = 229.35

In [52]:
df2

,R&D Spend,Administration,Marketing Spend
21,78.00,154.00,300.00
37,205.53,51.00,197.00
2,153.00,101.00,408.00
14,120.00,96.06,257.00
44,22.00,155.00,229.35


In [53]:
df2 - df1

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.00
37,-24.97,0.00,0.00
2,0.00,0.00,0.00
14,0.00,-17.49,0.00
44,0.00,0.00,-34.67


In [55]:
df3 = df2.copy()
df3.iloc[1,0] = np.nan
df3

,R&D Spend,Administration,Marketing Spend
21,78.0,154.00,300.00
37,NaN,51.00,197.00
2,153.0,101.00,408.00
14,120.0,96.06,257.00
44,22.0,155.00,229.35


In [56]:
X = df3.iloc[[0,2,3,4], 1 : 3]
y = df3.iloc[[0,2,3,4], 0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([144.47236596])

In [57]:
df3.iloc[1,0] = 144.47

In [58]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4] , [0,2]]
y = df3.iloc[[0,2,3,4], 0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([118.34362355])

In [59]:
df3.iloc[3,1] = 118.34


In [60]:
df3.iloc[4,-1] = np.nan
X = df3.iloc[0: 4 , 0: 2]
y = df3.iloc[0: 4 , -1]

lr = LinearRegression()
lr.fit(X , y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([73.46444049])

In [61]:
df3.iloc[4,-1] = 73.46

In [62]:
df2.iloc[3,1] = 96.06

In [63]:
df3

,R&D Spend,Administration,Marketing Spend
21,78.00,154.00,300.00
37,144.47,51.00,197.00
2,153.00,101.00,408.00
14,120.00,118.34,257.00
44,22.00,155.00,73.46


In [64]:
df3 - df2

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.00
37,-61.06,0.00,0.00
2,0.00,0.00,0.00
14,0.00,22.28,0.00
44,0.00,0.00,-155.89
